# Generated by Django 5.1.6 on 2025-03-17 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_token_expires_at_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 1, 47, 17, 26989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('job_seeker', 'JOB_SEEKER'), ('employer', 'EMPLOYER')], default='job_seeker', max_length=50),
        ),
    ]
