# Generated by Django 5.1.6 on 2025-03-17 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_token_expires_at_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 1, 48, 34, 822656, tzinfo=datetime.timezone.utc)),
        ),
    ]
