# Generated by Django 5.1.6 on 2025-03-17 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_token_expires_at_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 2, 15, 5, 478306, tzinfo=datetime.timezone.utc)),
        ),
    ]
