# Generated by Django 5.1.6 on 2025-03-17 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_token_expires_at_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 13, 49, 20, 101832, tzinfo=datetime.timezone.utc)),
        ),
    ]
