# Generated by Django 5.1.6 on 2025-03-17 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 15, 21, 21, 857971, tzinfo=datetime.timezone.utc)),
        ),
    ]
