# Generated by Django 5.1.6 on 2025-03-17 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_jobseeker_phone_number_alter_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='job_seeker_photos/'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='job_seeker_resumes/'),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 22, 32, 57, 665418, tzinfo=datetime.timezone.utc)),
        ),
    ]
