# Generated by Django 5.1.6 on 2025-03-18 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_jobseeker_profile_photo_alter_jobseeker_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 4, 50, 46, 534552, tzinfo=datetime.timezone.utc)),
        ),
    ]
