# Generated by Django 5.1.6 on 2025-03-18 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 14, 25, 32, 391752, tzinfo=datetime.timezone.utc)),
        ),
    ]
