# Generated by Django 5.1.6 on 2025-03-22 01:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_company_logo_alter_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+9989' and be followed by 8 digits.", regex='^\\+?[0-9]{12,15}$')]),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 1, 28, 37, 3725, tzinfo=datetime.timezone.utc)),
        ),
    ]
