# Generated by Django 5.1.6 on 2025-03-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Hard Skill', 'Hard Skill'), ('Soft Skill', 'Soft Skill'), ('Programming', 'Programming'), ('Design', 'Design'), ('Management', 'Management'), ('Data Science', 'Data Science'), ('Marketing', 'Marketing'), ('Framework', 'Framework')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
