# Generated by Django 5.1.6 on 2025-03-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_later', models.TextField()),
                ('resume', models.FileField(upload_to='job_application_resumes/')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Under review', 'Under review'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Offered', 'Offered'), ('Hired', 'Hired')], max_length=30)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=30)),
                ('experience_level', models.CharField(choices=[('Entry', 'Entry'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('Executive', 'Executive')], max_length=20)),
                ('education_required', models.CharField(choices=[('High School', 'High School'), ('Bachelors', "Bachelor's Degree"), ('Masters', "Master's Degree"), ('PhD', 'PhD')], max_length=30)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField()),
                ('views_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
